#ifndef TUI_INPUT_UNICODE_HPP_
#define TUI_INPUT_UNICODE_HPP_
namespace tui {
  enum Unicode {
    UTF_FULL_BLOCK = 9608,
    UTF_DARK_SHADE = 9619,
    UTF_MEDIUM_SHADE = 9618,
    UTF_LIGHT_SHADE = 9617,
    UTF_HORIZONTAL = 9473,
    UTF_VERTICAL = 9475,
    UTF_HORIZONTAL_DOUBLE_DASH = 9549,
    UTF_VERTICAL_DOUBLE_DASH = 9551,
    UTF_HORIZONTAL_TRIPLE_DASH = 9477,
    UTF_VERTICAL_TRIPLE_DASH = 9479
  };
}  // namespace tui
#endif  // TUI_INPUT_UNICODE_HPP_
