/* Copyright (C)
 * 2017 - Arden Rasmussen
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 *
 */

/**
 * @file unicode.hpp
 * @brief Unicode characters
 * @author Arden Rasmussen
 * @version 1.0
 * @date 2017-12-01
 */
#ifndef TUI_INPUT_UNICODE_HPP_
#define TUI_INPUT_UNICODE_HPP_
namespace tui {
  /**
   * @brief List of unicode characters.
   *
   * This contains a subset of unicode characters that can be used in TUI. These
   * represent the integer values instead of the hexadecimal values.
   */
  enum Unicode {
    UTF_LIGHT_HORIZONTAL = 9472,
    UTF_HEAVY_HORIZONTAL = 9473,
    UTF_LIGHT_VERTICAL = 9474,
    UTF_HEAVY_VERTICAL = 9475,
    UTF_LIGHT_TRIPLE_DASH_HORIZONTAL = 9476,
    UTF_HEAVY_TIRPLE_DASH_HORIZONTAL = 9477,
    UTF_LIGHT_TIRPLE_DASH_VERTICAL = 9478,
    UTF_HEAVY_TRIPLE_DASH_VERTICAL = 9479,
    UTF_LIGHT_QUADRUPLE_DASH_HORIZONTAL = 9480,
    UTF_HEAVY_QUADRUPLE_DASH_HORIZONTAL = 9481,
    UTF_LIGHT_QUADRUPLE_DASH_VERTICAL = 9482,
    UTF_HEAVY_QUADRUPLE_DASH_VERTICAL = 9483,
    UTF_LIGHT_DOWN_RIGHT = 9484,
    UTF_LIGHT_DOWN_HEAVY_RIGHT = 9485,
    UTF_HEAVY_DOWN_LIGHT_RIGHT = 9486,
    UTF_HEAVY_DOWN_RIGHT = 9487,
    UTF_LIGHT_DOWN_LEFT = 9488,
    UTF_LIGHT_DOWN_HEAVY_LEFT = 9489,
    UTF_HEAVY_DOWN_LIGHT_LEFT = 9490,
    UTF_HEAVY_DOWN_LEFT = 9491,
    UTF_LIGHT_UP_RIGHT = 9492,
    UTF_LIGHT_UP_HEAVY_RIGHT = 9493,
    UTF_HEAVY_UP_LIGHT_RIGHT = 9494,
    UTF_HEAVY_UP_RIGHT = 9495,
    UTF_LIGHT_UP_LEFT = 9496,
    UTF_LIGHT_UP_HEAVY_LEFT = 9497,
    UTF_HEAVY_UP_LIGHT_LEFT = 9498,
    UTF_HEAVY_UP_LEFT = 9499,
    UTF_LIGHT_VERTICAL_RIGHT = 9500,
    UTF_LIGHT_VERTICAL_HEAVY_RIGHT = 9501,
    UTF_HEAVY_UP_LIGHT_RIGHT_DOWN = 9502,
    UTF_HEAVY_DOWN_LIGHT_RIGHT_UP = 9503,
    UTF_HEAVY_VERTICAL_LIGHT_RIGHT = 9504,
    UTF_LIGHT_DOWN_HEAVY_RIGHT_UP = 9505,
    UTF_LIGHT_UP_HEAVY_RIGHT_DOWN = 9506,
    UTF_HEAVY_VERTICAL_RIGHT = 9507,
    UTF_LIGHT_VERTICAL_LEFT = 9508,
    UTF_LIGHT_VERTICAL_HEAVY_LEFT = 9509,
    UTF_HEAVY_UP_LIGHT_LEFT_DOWN = 9510,
    UTF_HEAVY_DOWN_LIGHT_LEFT_UP = 9511,
    UTF_HEAVY_VERTICAL_LIGHT_LEFT = 9512,
    UTF_LIGHT_DOWN_HEAVY_LEFT_UP = 9513,
    UTF_LIGHT_UP_HEAVY_LEFT_DOWN = 9514,
    UTF_HEAVY_VERTICAL_LEFT = 9515,
    UTF_LIGHT_DOWN_HORIZONTAL = 9516,
    UTF_HEAVY_LEFT_LIGHT_RIGHT_DOWN = 9517,
    UTF_HEAVY_RIGHT_LIGHT_LEFT_DOWN = 9518,
    UTF_LIGHT_DOWN_HEAVY_HORIZONTAL = 9519,
    UTF_HEAVY_DOWN_LIGHT_HORIZONTAL = 9520,
    UTF_LIGHT_RIGHT_HEAVY_LEFT_DOWN = 9521,
    UTF_LIGHT_LEFT_HEAVY_RIGHT_DOWN = 9522,
    UTF_HEAVY_DOWN_HORIZONTAL = 9523,
    UTF_LIGHT_UP_HORIZONTAL = 9524,
    UTF_HEAVY_LEFT_LIGHT_RIGHT_UP = 9525,
    UTF_HEAVY_RIGHT_LIGHT_LEFT_UP = 9526,
    UTF_LIGHT_UP_HEAVY_HORIZONTAL = 9527,
    UTF_HEAVY_UP_LIGHT_HORIZONTAL = 9528,
    UTF_LIGHT_RIGHT_HEAVY_LEFT_UP = 9529,
    UTF_LIGHT_LEFT_HEAVY_RIGHT_UP = 9530,
    UTF_HEAVY_UP_HORIZONTAL = 9531,
    UTF_LIGHT_VERTICAL_HORIZONTAL = 9532,
    UTF_HEAVY_LEFT_LIGHT_RIGHT_VERTICAL = 9533,
    UTF_HEAVY_RIGHT_LIGHT_LEFT_VERTICAL = 9534,
    UTF_LIGHT_VERTICAL_HEAVY_HORIZONTAL = 9535,
    UTF_HEAVY_UP_LIGHT_DOWN_HORIZONTAL = 9536,
    UTF_HEAVY_DOWN_LIGHT_UP_HORIZONTAL = 9537,
    UTF_HEAVY_VERTICAL_LIGHT_HORIZONTAL = 9538,
    UTF_HEAVY_LEFT_UP_LIGHT_RIGHT_DOWN = 9539,
    UTF_HEAVY_RIGHT_UP_LIGHT_LEFT_DOWN = 9540,
    UTF_HEAVY_LEFT_DOWN_LIGHT_RIGHT_UP = 9541,
    UTF_HEAVY_RIGHT_DOWN_LIGHT_LEFT_UP = 9542,
    UTF_LIGHT_DOWN_HEAVY_UP_HORIZONTAL = 9543,
    UTF_LIGHT_UP_HEAVY_DOWN_HORIZONTAL = 9544,
    UTF_LIGHT_RIGHT_HEAVY_LEFT_VERTICAL = 9545,
    UTF_LIGHT_LEFT_HEAVY_RIGHT_VERTICAL = 9546,
    UTF_HEAVY_VERTICAL_HORIZONTAL = 9547,
    UTF_LIGHT_DOUBLE_DASH_HORIZONTAL = 9548,
    UTF_HEAVY_DOUBLE_DASH_HORIZONTAL = 9549,
    UTF_LIGHT_DOUBLE_DASH_VERTICAL = 9550,
    UTF_HEAVY_DOUBLE_DASH_VERTICAL = 9551,
    UTF_UPPER_HALF_BLOCK = 9600,
    UTF_LOWER_ONE_EIGHTH_BLOCK = 9601,
    UTF_LOWER_ONE_QUARTER_BLOCK = 9602,
    UTF_LOWER_THREE_EIGHTHS_BLOCK = 9603,
    UTF_LOWER_HALF_BLOCK = 9604,
    UTF_LOWER_FIVE_EIGHTHS_BLOCK = 9605,
    UTF_LOWER_THREE_QUARTERS_BLOCK = 9606,
    UTF_LOWER_SEVEN_EIGHTHS_BLOCK = 9607,
    UTF_FULL_BLOCK = 9608,
    UTF_LEFT_SEVEN_EIGHTHS_BLOCK = 9609,
    UTF_LEFT_THREE_QUARTERS_BLOCK = 9610,
    UTF_LEFT_FIVE_EIGHTHS_BLOCK = 9611,
    UTF_LEFT_HALF_BLOCK = 9612,
    UTF_LEFT_THREE_EIGHTHS_BLOCK = 9613,
    UTF_LEFT_ONE_QUARTER_BLOCK = 9614,
    UTF_LEFT_ONE_EIGHTH_BLOCK = 9615,
    UTF_RIGHT_HEALF_BLOCK = 9616,
    UTF_LIGHT_SHADE = 9617,
    UTF_MEDIUM_SHADE = 9618,
    UTF_DARK_SHADE = 9619
  };
}  // namespace tui
#endif  // TUI_INPUT_UNICODE_HPP_
